# Generated by Django 2.0.2 on 2018-12-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('image_class', models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Image'), (1, 'Photo'), (2, 'Screenshot')], default=-1)),
            ],
        ),
    ]
