PYVERSION=3.5
NAME=ips_classifier
REPO=vlaand
VERSION=latest

docker build -t '$(REPO)/$(NAME):$(VERSION)' -f Dockerfile .;

#docker build -t vlaand/ips_classifier:latest -f Dockerfile .
#docker run --rm -p 8000:8000 -ti vlaand/ips_classifier:latest